Work in progress...
Signed-off-by: Emanuele Ballarin <emanuele@ballarin.cc>

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
-# File generated by: pre-commit <https://pre-commit.com>
+# File generated by pre-commit: https://pre-commit.com
+# ID: 138fd403232d2ddd5efb44317e38bf03
 
 # start templated
-INSTALL_PYTHON="$HOME/.local/pipx/venvs/pre-commit/bin/python"
+INSTALL_PYTHON=/usr/bin/python
 ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
 # end templated
 
@@ -14,6 +15,6 @@ if [ -x "$INSTALL_PYTHON" ]; then
 elif command -v pre-commit > /dev/null; then
     exec pre-commit "${ARGS[@]}"
 else
-    echo "'pre-commit' not found.  Did you forget to activate your virtualenv?" 1>&2
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
     exit 1
 fi
